"""add product description discount category brand stock unit weight colors

Revision ID: 1fa64a5ae35f
Revises: 001
Create Date: 2026-03-02 22:43:29.080651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1fa64a5ae35f"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("description_ar", sa.Text(), nullable=True))
    op.add_column("products", sa.Column("description_en", sa.Text(), nullable=True))
    op.add_column(
        "products",
        sa.Column(
            "discount_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
    )
    op.add_column(
        "products",
        sa.Column("discounted_price", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column("products", sa.Column("category", sa.String(), nullable=True))
    op.add_column("products", sa.Column("brand", sa.String(), nullable=True))
    op.add_column("products", sa.Column("stock_qty", sa.Integer(), nullable=True))
    op.add_column(
        "products",
        sa.Column("unit", sa.String(), server_default="piece", nullable=False),
    )
    op.add_column(
        "products", sa.Column("weight", sa.Numeric(precision=8, scale=2), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column(
            "color_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "color_options")
    op.drop_column("products", "weight")
    op.drop_column("products", "unit")
    op.drop_column("products", "stock_qty")
    op.drop_column("products", "brand")
    op.drop_column("products", "category")
    op.drop_column("products", "discounted_price")
    op.drop_column("products", "discount_percentage")
    op.drop_column("products", "description_en")
    op.drop_column("products", "description_ar")
    # ### end Alembic commands ###
