"""add_company_ledger_table

Revision ID: 427a4d983a8e
Revises: f2a3b4c5d6e7
Create Date: 2026-03-06 13:45:12.276104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427a4d983a8e'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_ledger',
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='ledgerdirection', create_constraint=True), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'check', name='ledgerpaymentmethod', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rep_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('source_transaction_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'flagged', name='ledgerstatus', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_notes', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_transaction_id')
    )
    op.create_index('ix_company_ledger_date', 'company_ledger', ['date'], unique=False)
    op.create_index('ix_company_ledger_direction', 'company_ledger', ['direction'], unique=False)
    op.create_index('ix_company_ledger_rep_id', 'company_ledger', ['rep_id'], unique=False)
    op.create_index('ix_company_ledger_status', 'company_ledger', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_ledger_status', table_name='company_ledger')
    op.drop_index('ix_company_ledger_rep_id', table_name='company_ledger')
    op.drop_index('ix_company_ledger_direction', table_name='company_ledger')
    op.drop_index('ix_company_ledger_date', table_name='company_ledger')
    op.drop_table('company_ledger')
    sa.Enum(name='ledgerdirection').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ledgerpaymentmethod').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ledgerstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
