"""add customer_auth table and is_draft to transactions

Revision ID: 4d494ecdfd14
Revises: f2d175c206a1
Create Date: 2026-03-03 12:54:05.822511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d494ecdfd14"
down_revision: Union[str, None] = "f2d175c206a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_auth",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id"),
    )
    op.create_index(
        op.f("ix_customer_auth_phone"), "customer_auth", ["phone"], unique=True
    )
    op.add_column(
        "transactions",
        sa.Column(
            "is_draft", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.alter_column(
        "transactions", "created_by", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions", "created_by", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("transactions", "is_draft")
    op.drop_index(op.f("ix_customer_auth_phone"), table_name="customer_auth")
    op.drop_table("customer_auth")
    # ### end Alembic commands ###
