"""add delivered_date to transactions

Revision ID: c0e5f58f9eca
Revises: 6b2c3d4e5f6a
Create Date: 2026-03-03 14:59:05.941026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c0e5f58f9eca"
down_revision: Union[str, None] = "6b2c3d4e5f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("delivered_date", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_transactions_delivered_date"),
        "transactions",
        ["delivered_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_delivered_date"), table_name="transactions")
    op.drop_column("transactions", "delivered_date")
    # ### end Alembic commands ###
