"""add customer phone address location avatar notes

Revision ID: f2d175c206a1
Revises: 1fa64a5ae35f
Create Date: 2026-03-02 22:43:58.410547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f2d175c206a1"
down_revision: Union[str, None] = "1fa64a5ae35f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("customers", sa.Column("address", sa.String(), nullable=True))
    op.add_column(
        "customers",
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
    )
    op.add_column(
        "customers",
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
    )
    op.add_column("customers", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("customers", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "notes")
    op.drop_column("customers", "avatar_url")
    op.drop_column("customers", "longitude")
    op.drop_column("customers", "latitude")
    op.drop_column("customers", "address")
    op.drop_column("customers", "phone")
    # ### end Alembic commands ###
